name: Lint, Test & Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v3
      - name: Install Environment (NodeJS)
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies for project
        run: npm ci
      - name: Code Linting
        run: npm lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v3
      - name: Install Environment (NodeJS)
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies for project
        run: npm ci
      - name: Run Unit Test
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v3
      - name: Install Environment (NodeJS)
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies for project
        run: npm ci
      - name: Deploy to Host
        run: echo "Deploying..."