name: Lint, Test & Deploy
on: push
jobs: # alternatively, all can be run on a single job
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v3
      - name: Install Environment (NodeJS)
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies for project
        run: npm ci
      - name: Code Linting
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v3
      - name: Install Environment (NodeJS)
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies for project
        run: npm ci
      - name: Run Unit Test
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v3
      - name: Install Environment (NodeJS)
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies for project
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy to Host
        run: echo "Deploying..."